name: Automated API tests using Postman CLI

on:
  push:
    branches: 
      - main

env: 
  BASE_URI: 'https://simple-books-api.glitch.me'
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
  POSTMAN_COLLECTION_UID: '31058211-a8638445-9b84-4f65-abba-1ad8582069b9'
  POSTMAN_ENVIRONMENT_UID: '31058211-73f0e4c8-2004-40f7-ac9e-05ae44550993'

jobs:
  automated-api-tests:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Newman
        run: |
          npm install -g newman
      - name: Install Newman Reporter
        run: |
          npm install -g newman-reporter-html
      - name: Fetch postman collection
        run: |
          curl -X GET newman run "https://api.getpostman.com/collections/${POSTMAN_COLLECTION_UID}" \
          -H "X-Api-Key: ${POSTMAN_API_KEY}" > collection.json
        shell: bash
      - name: Fetch postman environment
        run: |
          curl -X GET newman run "https://api.getpostman.com/collections/${POSTMAN_ENVIRONMENT_UID}" \
          -H "X-Api-Key: ${POSTMAN_API_KEY}" > environment.json
      - name: Run API tests
        run: |
          newman collection.json --environment environment.json --reporters cli,html --reporter-html-export "report.html"
      - name: Upload report
        uses: actions/upload-artifact@v4
        with: 
          name: report
          path: report.html