name: Automated API tests using Postman CLI

on:
  schedule: 
    - cron: '*/1 * * * *'

env: 
  BASE_URI: 'https://simple-books-api.glitch.me'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "31058211-a8638445-9b84-4f65-abba-1ad8582069b9" -e "31058211-73f0e4c8-2004-40f7-ac9e-05ae44550993"